/* tslint:disable */
// @ts-nocheck
const { writeFile, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs');

require('dotenv').config();
const environment = argv.environment;

function writeFileUsingFS(targetPath, environmentFileContent) {
  writeFile(targetPath, environmentFileContent, function (err) {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== '') {
      console.log(`wrote variables to ${targetPath}`);
    }
  });
}

// Providing path to the `environments` directory
const envDirectory = './projects/details/src/infrastructure/environments';

// creates the `environments` directory if it does not exist
if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

//creates the `environment.prod.ts` and `environment.ts` file if it does not exist
writeFileUsingFS(
  './projects/details/src/infrastructure/environments/environment.prod.ts',
  ''
);
writeFileUsingFS(
  './projects/details/src/infrastructure/environments/environment.ts',
  ''
);

// Checks whether command line argument of `prod` was provided signifying production mode
const isProduction = environment === 'prod';

// choose the correct targetPath based on the environment chosen
const targetPath = isProduction
  ? './projects/details/src/infrastructure/environments/environment.prod.ts'
  : './projects/details/src/infrastructure/environments/environment.ts';

//actual content to be compiled dynamically and pasted into respective environment files
const environmentFileContent = `
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy

  export const environment = {
    production: ${isProduction},
    baseURL: 'https://api.themoviedb.org/3',
    language: 'en-US',
    paramsDefault: 'api_key=${process.env.API_KEY}&language=en-US',
    imageApi: {
      base_url: 'http://image.tmdb.org/t/p',
      secure_base_url: 'https://image.tmdb.org/t/p',
      backdrop_sizes: {
        w300: 'w300',
        w780: 'w780',
        w1280: 'w1280',
        original: 'original',
      },
      logo_sizes: {
        w45: 'w45',
        w92: 'w92',
        w154: 'w154',
        w185: 'w185',
        w300: 'w300',
        w500: 'w500',
        original: 'original',
      },
      poster_sizes: {
        w92: 'w92',
        w154: 'w154',
        w185: 'w185',
        w342: 'w342',
        w500: 'w500',
        w780: 'w780',
        original: 'original',
      },
      profile_sizes: {
        w45: 'w45',
        w185: 'w185',
        h632: 'h632',
        original: 'original',
      },
      still_sizes: {
        w92: 'w92',
        w185: 'w185',
        w300: 'w300',
        original: 'original',
      },
    },
  };
`;

writeFileUsingFS(targetPath, environmentFileContent); // appending data into the target file

/* tslint:enable */
